Blog App - processing data in models
harshi0102/blog-app-rails pull request #2
Opened 2023-07-19 16:39 UTC by harshi0102

2023-07-19 17:26 UTC, zainsadaqat requested changes
# Required Changes 🔁
## Hello @harshi0102  👋 🙂

You're doing a great job on your project. We're proud of you. Good job so far! 

It's OK to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job. 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Flow
  ✅  Descriptive Pull Request
  ✅  No linter errors

## Required Changes ♻️

- [ ] 

<img src="https://media0.giphy.com/media/HxnMNAEQgHqEHcGKBb/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 17:26 UTC, zainsadaqat commented on app/models/user.rb
> -  has_many :likes, dependent: :destroy
Dear @harshi0102 
Good job for adding the user's relation with posts However, there're two relations that are missing. As you can see in the ERD diagram. The user also has many Likes and User has many Comments. Kindly implement that as well 👍 

<img width="823" alt="Screenshot 2023-07-19 at 10 21 46 PM" src="https://github.com/harshi0102/blog-app-rails/assets/83048208/4a2a89da-3a4f-4943-b608-c6f1886873c1">

2023-07-19 17:26 UTC, zainsadaqat commented on app/models/post.rb
> +  after_create :update_user_posts_counter
### [OPTIONAL]
Dear @harshi0102 
You can also use one of the [Rails Active Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html) - after_save

2023-07-19 17:26 UTC, zainsadaqat commented on app/models/like.rb
> +  after_destroy :update_post_likes_counter
[OPTIONAL]
Dear @harshi0102
You can also use one of the [Rails Active Callbacks](https://guides.rubyonrails.org/active_record_callbacks.html) - after_save

2023-07-20 10:10 UTC, elisha2kyakpo1 approved these changes
Hi 👋 @harshi0102, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 You did well implementing the changes requested by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 10:11 UTC, merged