Blog app: add devise
harshi0102/blog-app-rails pull request #9
Opened 2023-08-02 09:40 UTC by harshi0102

2023-08-02 11:25 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @harshi0102 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![0bd223a2b156e0eaf61a713e84c3d3b7](https://user-images.githubusercontent.com/57408419/255594021-109e7375-12de-4f5b-9e29-79eefc52e35a.gif)



## To highlight :champagne: 

- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 11:25 UTC, joel-kalema commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] You did a good job adding devise 🥇, however, make sure the `:confirmable` is enabled in the user model 👍. this is to make the application asks for confirmation of email. It'll be something like this:

```ruby
devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :validatable, :confirmable
``` 

Kindly, fix it 😃

2023-08-03 10:45 UTC, harshi0102 commented
**According to the previous feedback  , I added confirmable to the user model -** 
https://github.com/harshi0102/blog-app-rails/blob/969e80fc6eed08aaf8118d8ebad37f4655f14440/app/models/user.rb#L5

**The confirmation token needs to be clicked before signing to the page. After verifiying I have a screenshot below which generates confirmation token for login to the page successfully.**

![image](https://github.com/harshi0102/blog-app-rails/assets/108334376/99cd799e-80c8-414c-b74a-86278d4601ea)

2023-08-03 11:41 UTC, Munsa1 approved these changes
Hi @harshi0102, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Made Requested Change By Previous Reviewer :heavy_check_mark: 

## Optional suggestions
- [ ] Check inline comments

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-03 11:41 UTC, Munsa1 commented on app/views/devise/registrations/new.html.erb
> +      <%= f.text_area :bio, autofocus: true,  placeholder: "bio",autocomplete: "bio" %>
- [ ] (optional) Consider matching the given wireframe for your Sign up and Login page so as to fully meet the given requirements

Your design
![image](https://github.com/harshi0102/blog-app-rails/assets/81932478/8096ef91-9e7c-4ee6-9ace-3e55291d31f4)

Given wireframe
![image](https://github.com/harshi0102/blog-app-rails/assets/81932478/7ce7d9e7-5a02-40cc-9d97-53d792c04cca)

Check project [requirement bullet point number three](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md)
![image](https://github.com/harshi0102/blog-app-rails/assets/81932478/f277ec28-a6ac-4d0c-9d9b-205190be403c)

2023-08-03 11:42 UTC, merged